### ISSUE TITLE
Use on a Raspberry Pi 3

### ISSUE THREAD

**Issue by remaclepi** [alex-mous/VL53L1X-C-API-Pico#1]
Hello, how can I adapt your code for a Raspberry Pi 3 and not a pico ? I'm looking for standard C, and I'm not very familiar with the pico.

Any hints on how I should do that ? Is it even possible ?

Thanks a lot if you can help.

**Comment by alex-mous** [comment]
This project is specifically dedicated to supporting the VL53L1x on Raspberry Pi Picos, which are microcontrollers unlike the Raspberry Pi 3 which is a computer and supports IO differently - so I wouldn’t recommend trying to port this code over to use on a Raspberry Pi computer. I believe there are several other libraries that will support this sensor on a Raspberry Pi.

Hope that helps.
