### ISSUE TITLE
Error initializing sensor

### ISSUE THREAD

**Issue by MrcsLSF** [alex-mous/VL53L1X-C-API-Pico#2]
# Hardware.
Im using:
* Raspberry PI pico_w
* MappyDot Plus (VL53L1X)

# Software

I loaded the example `continuous_measuring.c` from this library.

pico_w | MappyDot
:----:|:----:
3v3|VCC
GND|GND
GPIO4 | SDA
GPIO5| SCL

# Problems & Troubleshooting

I ran this example and get the following errror: `Error initializing sensor`
i've also ran the code without sensors and get same error
I ran another code that scans i2c adresses and detected the sensor.

I've tried everything above with external pullup resistors.

**Comment by alex-mous** [comment]
Could you please verify if the MappyDot Plus uses the same protocol/driver firmware as the standard VL53L1X? This API was designed for VL53L1X breakout boards, so, if there's a difference in the MappyDot I2C API, I'm afraid this library won't help without modification.
